### ISSUE TITLE
model-util: Add support for data-type Formats offered by the OAS

### ISSUE THREAD

**Issue by nbhusare** [adobe/ride#25]
### Expected Behaviour
Model Utility only supports a subset of [built-in formats](https://json-schema.org/understanding-json-schema/reference/string.html#built-in-formats) from the JSON Schema Spec. In addition, it should support the [additional formats ](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#dataTypeFormat)offered by the OAS.

Alternative - The `format` property can have any value. If the Model Utility fails in identifying the format, or if the format is not specified, it should fall back to the `type` property. 
 
### Actual Behaviour
Fails with the following error - `UnexpectedModelPropertyTypeException: Encountered unexpected model property type when loading model: {"format":"int64"...}`

The error is not clear. It does not explain the actual failure condition. 

#### Sample Code that illustrates the problem
```
val schema = {"type":"array",                             
"items":{                                    
	"type":"object",                         
	"required":[                             
		"id"                                 
	],                                       
	"properties":{                           
		"id":{                               
			"type":"integer","format":"int64"
		}                                    
	}                                        
}}
val responseObj = new ModelObject(sampleSchema, false);
responseObj.buildValidModelInstance();                       
```

#### Logs taken while reproducing problem
```
com.adobe.ride.utilities.model.exceptions.UnexpectedModelPropertyTypeException: Encountered unexpected model property type when loading model: {"format":"int64","type":"integer"}
	at com.adobe.ride.utilities.model.ModelObject.getModelPropertyType(ModelObject.java:450)
	at com.adobe.ride.utilities.model.ModelObject.generateNodeValue(ModelObject.java:1162)
	at com.adobe.ride.utilities.model.ModelObject.buildObjectNode(ModelObject.java:729)
	at com.adobe.ride.utilities.model.ModelObject.generateNodeValue(ModelObject.java:1319)
	at com.adobe.ride.utilities.model.ModelObject.buildArrayNode(ModelObject.java:812)
	at com.adobe.ride.utilities.model.ModelObject.buildValidModelInstance(ModelObject.java:516)
```

**Comment by tedcasey** [comment]
Noted at a work item to be scheduled and implemented.  More information about this issue will be posted as it becomes available.

**Comment by tedepstein** [comment]
Thanks, @tedcasey . 

This is really two issues: 

1. If the `format` property value is unrecognized, then format should be ignored for validation purposes, and model-util can generate the example based on the `type` and other specified constraints.
2. It would be helpful for model-util to recognize the OpenAPI formats [described here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#data-types), and generate conformant values for these.

The first issue is the one that's blocking us now, as we can't get around it except by removing `format`  from the input schema. We haven't done a complete analysis, but we think it should be pretty easy to fix.

If you are planning to address that issue right away (this week or next week, maybe), we can wait. Otherwise, would you like us to submit a pull request with a proposed fix? If the fix passes your code review, how long (roughly) would you need to turn around a new patch release? 

Not trying to put undue pressure on you and your team, we just need to have a sense of your process and release cadence so we can determine the best way to collaborate on this.  Thanks!

**Comment by tedcasey** [comment]
In terms of release turnaround, we're pretty lightweight at this point.  So, probably a day or so turnaround.  It may get longer in the future, but the product is already somewhat mature, so maybe not.

In the meatime, if you have a PR in mind, feel free to open it up and I will review asap.

**Comment by tedcasey** [comment]
The fallback issue is fixed with the 1.0.5 release of Ride.  Thanks, Neeraj!

Adding support for the complete set of OAS formats is TBD.  The effort may be too large to be handled in one issue.  I propose closing this issue and open issues for as-yet unsupported OAS formats as they become required.  I'll leave this open for comments until an agreement can be reached.

**Comment by tedcasey** [comment]
No new comments in over a week.  I'll plan on closing this issue as too broad by Friday April 20th, unless someone comments before then and wants to tackle implementing data generation for rest of the full set of OAS string formats.

**Comment by tedepstein** [comment]
@tedcasey , I'd be OK closing this one and reopening individual issues as the need arises.

**Comment by tedcasey** [comment]
@tedepstein Ok, thanks, Ted!

**Comment by tedcasey** [comment]
New Issue logged.  Thanks, Ted!

Closing this issue.
